import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const AuthPagesLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <main className="flex min-h-full items-center justify-center p-4">
      {children}
    </main>
  )
}

export default AuthPagesLayout
