import type { Metadata } from "next"
import type { PropsWithChildren } from "react"
import ThemeToggle from "@/components/layout/ThemeToggle"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const AuthPagesLayout = ({ children }: PropsWithChildren) => {
  return (
    <main className="relative flex min-h-full items-center justify-center p-4">
      <div className="absolute top-4 right-4">
        <ThemeToggle />
      </div>
      {children}
    </main>
  )
}

export default AuthPagesLayout
