import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const UserAreaLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return <div>{children}</div>
}

export default UserAreaLayout
